//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApp.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **NOTE:** November 15th, 2020 BCHA fork.
        /// </summary>
        public static string BCH_2020_Hardfork {
            get {
                return ResourceManager.GetString("BCH_2020_Hardfork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billion.
        /// </summary>
        public static string Billion {
            get {
                return ResourceManager.GetString("Billion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Block.
        /// </summary>
        public static string BlockHeight {
            get {
                return ResourceManager.GetString("BlockHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookies on this site help to enhance your user experience. By continuing to browse our website you are agreeing to how we use cookies. You can change your browser cookie settings at any time..
        /// </summary>
        public static string CookieWarning {
            get {
                return ResourceManager.GetString("CookieWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Mode.
        /// </summary>
        public static string DarkMode {
            get {
                return ResourceManager.GetString("DarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Stratum Protocol Configuration&lt;/b&gt;
        ///&lt;br/&gt;
        ///&lt;ul&gt;
        ///&lt;li&gt;Claymore Miner: Add the &lt;code&gt;-esm 3&lt;/code&gt; command line switch&lt;/li&gt;
        ///&lt;li&gt;Ethminer/Genoil: Add the &lt;code&gt;-SP 2&lt;/code&gt; command line switch&lt;/li&gt;
        ///&lt;/ul&gt;.
        /// </summary>
        public static string EthStratumInstructions {
            get {
                return ResourceManager.GetString("EthStratumInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you provide an API?.
        /// </summary>
        public static string FaqAPI {
            get {
                return ResourceManager.GetString("FaqAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Yes, of course.](/api).
        /// </summary>
        public static string FaqAPIAnswer {
            get {
                return ResourceManager.GetString("FaqAPIAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why is my reported hashrate zero or different from what my miner reports?.
        /// </summary>
        public static string FaqHashrate {
            get {
                return ResourceManager.GetString("FaqHashrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pool and miner hashrates are re-calculated every ten minutes. Therefore it can take a maximum of ten minutes for your hashrate to update depending on the submission time of your first valid share. The hashrate we display at the pool is a rough approximation of your hashrate based on your submitted shares and can therefore differ significantly from the hashrate displayed locally. When in doubt always consider the value displayed by your miner as the correct one..
        /// </summary>
        public static string FaqHashrateAnswer {
            get {
                return ResourceManager.GetString("FaqHashrateAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How will I get paid?.
        /// </summary>
        public static string FaqPayouts {
            get {
                return ResourceManager.GetString("FaqPayouts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When will I get paid?.
        /// </summary>
        public static string FaqPayouts2 {
            get {
                return ResourceManager.GetString("FaqPayouts2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You won&apos;t see any balance in your account until a block has been found by the pool and after the block has reached a mature status. This may take a couple hours, depending on the coin. As soon as a block can be considered &apos;mature&apos; by the pool, your shares will be used to calculate your contribution towards finding the block. The more you&apos;ve contributed, the higher your cut of the block reward will be. Your cut of the block reward will then be credited to your pending balance. If your balance reaches or exce [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FaqPayouts2Answer {
            get {
                return ResourceManager.GetString("FaqPayouts2Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All of our non-solo pools utilize the &lt;a href=&quot;https://bitcointalk.org/index.php?topic=39832&quot;&gt;PPLNS&lt;/a&gt; payment system. &lt;a href=&quot;https://bitcointalk.org/index.php?topic=39832&quot;&gt;PPLNS&lt;/a&gt; is short for &quot;Pay Per Last N Shares&quot;. The image below illustrates the system. One round has an arbitrary number of shares which is solely based on sheer luck. Proportional reward systems only consider shares of one round when calculating rewards. PPLNS however, uses a quite constant number N of shares for calculating rewards [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FaqPayoutsAnswer {
            get {
                return ResourceManager.GetString("FaqPayoutsAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You keep talking about performance and reliability. What makes you think you are special?.
        /// </summary>
        public static string FaqPerformance {
            get {
                return ResourceManager.GetString("FaqPerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlike many other mining pools running on shared VPCs from the cheapest provider which often suffer from &quot;bad neighbor&quot; induced latency and performance drops, our pools run on dedicated hardware (Dual Hex-Core Xeons, 128 GB RAM) which are connected to the Internet using multiple high-bandwidth peerings guaranteeing low latency and stability..
        /// </summary>
        public static string FaqPerformanceAnswer {
            get {
                return ResourceManager.GetString("FaqPerformanceAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do I have to register somewhere to start mining?.
        /// </summary>
        public static string FaqRegistration {
            get {
                return ResourceManager.GetString("FaqRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration is not required.  Just configure your miner according to our instructions and start mining. Your first submitted share will automatically register you with our pool. Good Luck!.
        /// </summary>
        public static string FaqRegistrationAnswer {
            get {
                return ResourceManager.GetString("FaqRegistrationAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solo Mining.
        /// </summary>
        public static string FaqSoloMining {
            get {
                return ResourceManager.GetString("FaqSoloMining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Solo-Mining all miners compete with each other for the current block. The miner submitting the share with a difficulty representing the block, will receive the entire block-reward minus the negligible pool fee.
        ///.
        /// </summary>
        public static string FaqSoloMiningAnswer {
            get {
                return ResourceManager.GetString("FaqSoloMiningAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting started.
        /// </summary>
        public static string GettingStarted {
            get {
                return ResourceManager.GetString("GettingStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string GoWalletButtonCaption {
            get {
                return ResourceManager.GetString("GoWalletButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hashrate.
        /// </summary>
        public static string Hashrate {
            get {
                return ResourceManager.GetString("Hashrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deutsch.
        /// </summary>
        public static string Language_de {
            get {
                return ResourceManager.GetString("Language_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Language_en {
            get {
                return ResourceManager.GetString("Language_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Español.
        /// </summary>
        public static string Language_es {
            get {
                return ResourceManager.GetString("Language_es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Français.
        /// </summary>
        public static string Language_fr {
            get {
                return ResourceManager.GetString("Language_fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to हिंदी.
        /// </summary>
        public static string Language_hi {
            get {
                return ResourceManager.GetString("Language_hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italiano.
        /// </summary>
        public static string Language_it {
            get {
                return ResourceManager.GetString("Language_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日本語.
        /// </summary>
        public static string Language_ja {
            get {
                return ResourceManager.GetString("Language_ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 한국어.
        /// </summary>
        public static string Language_ko {
            get {
                return ResourceManager.GetString("Language_ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Português.
        /// </summary>
        public static string Language_pt {
            get {
                return ResourceManager.GetString("Language_pt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский.
        /// </summary>
        public static string Language_ru {
            get {
                return ResourceManager.GetString("Language_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ไทย.
        /// </summary>
        public static string Language_th {
            get {
                return ResourceManager.GetString("Language_th", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Türkçe.
        /// </summary>
        public static string Language_tr {
            get {
                return ResourceManager.GetString("Language_tr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TiếngViệt.
        /// </summary>
        public static string Language_vi {
            get {
                return ResourceManager.GetString("Language_vi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 简体中文.
        /// </summary>
        public static string Language_zh {
            get {
                return ResourceManager.GetString("Language_zh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Block.
        /// </summary>
        public static string LastBlockTime {
            get {
                return ResourceManager.GetString("LastBlockTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Mode.
        /// </summary>
        public static string LightMode {
            get {
                return ResourceManager.GetString("LightMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Million.
        /// </summary>
        public static string Million {
            get {
                return ResourceManager.GetString("Million", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miner Earnings.
        /// </summary>
        public static string MinerEarnings {
            get {
                return ResourceManager.GetString("MinerEarnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miner Earnings.
        /// </summary>
        public static string MinerEarnings2 {
            get {
                return ResourceManager.GetString("MinerEarnings2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total earnings of all miners over the pool&apos;s lifetime.
        /// </summary>
        public static string MinerEarningsTooltip {
            get {
                return ResourceManager.GetString("MinerEarningsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payments.
        /// </summary>
        public static string MinerPayments {
            get {
                return ResourceManager.GetString("MinerPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miner Stats.
        /// </summary>
        public static string MinerStats {
            get {
                return ResourceManager.GetString("MinerStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workers.
        /// </summary>
        public static string MinerWorkers {
            get {
                return ResourceManager.GetString("MinerWorkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mining Pool.
        /// </summary>
        public static string MiningPool {
            get {
                return ResourceManager.GetString("MiningPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Mining Pools.
        /// </summary>
        public static string MiningPoolsHeader {
            get {
                return ResourceManager.GetString("MiningPoolsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pool.
        /// </summary>
        public static string MiningPoolShort {
            get {
                return ResourceManager.GetString("MiningPoolShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pool.
        /// </summary>
        public static string MiningPoolShortDetails {
            get {
                return ResourceManager.GetString("MiningPoolShortDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Payout.
        /// </summary>
        public static string MinPayout {
            get {
                return ResourceManager.GetString("MinPayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Payout to Exchange.
        /// </summary>
        public static string MinPayoutExchange {
            get {
                return ResourceManager.GetString("MinPayoutExchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miner Stats.
        /// </summary>
        public static string MyStats {
            get {
                return ResourceManager.GetString("MyStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Difficulty.
        /// </summary>
        public static string NetworkDifficulty {
            get {
                return ResourceManager.GetString("NetworkDifficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Hashrate.
        /// </summary>
        public static string NetworkHashrate {
            get {
                return ResourceManager.GetString("NetworkHashrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newbie Setup.
        /// </summary>
        public static string NewbieSetup {
            get {
                return ResourceManager.GetString("NewbieSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crypto mining pools.
        /// </summary>
        public static string OpenGraphAppDescription {
            get {
                return ResourceManager.GetString("OpenGraphAppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} | Fee {2}% PPLNS.
        /// </summary>
        public static string OpenGraphAppDescription_Pool {
            get {
                return ResourceManager.GetString("OpenGraphAppDescription_Pool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} | Fee {2}% PPLNS, Paid {3} {4}.
        /// </summary>
        public static string OpenGraphAppDescription_Pool_Paid {
            get {
                return ResourceManager.GetString("OpenGraphAppDescription_Pool_Paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Miningpool.
        /// </summary>
        public static string OpenGraphAppName {
            get {
                return ResourceManager.GetString("OpenGraphAppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crypto mining pools.
        /// </summary>
        public static string OpenGraphAppTitle {
            get {
                return ResourceManager.GetString("OpenGraphAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payout commission.
        /// </summary>
        public static string PayoutComission {
            get {
                return ResourceManager.GetString("PayoutComission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earnings.
        /// </summary>
        public static string PayoutScheme {
            get {
                return ResourceManager.GetString("PayoutScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To open your personal mining dashboard, click the **_Miner Stats_** tab to the right of this page, enter the wallet address you are mining with and click **_Load_**..
        /// </summary>
        public static string PersonalStats {
            get {
                return ResourceManager.GetString("PersonalStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block Effort.
        /// </summary>
        public static string PoolBlockEffort {
            get {
                return ResourceManager.GetString("PoolBlockEffort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average effort over last 15 blocks.
        /// </summary>
        public static string PoolBlockEffortTooltip {
            get {
                return ResourceManager.GetString("PoolBlockEffortTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocks.
        /// </summary>
        public static string PoolBlocks {
            get {
                return ResourceManager.GetString("PoolBlocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee.
        /// </summary>
        public static string PoolFee {
            get {
                return ResourceManager.GetString("PoolFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hashrate.
        /// </summary>
        public static string PoolHashrate {
            get {
                return ResourceManager.GetString("PoolHashrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting started.
        /// </summary>
        public static string PoolHelp {
            get {
                return ResourceManager.GetString("PoolHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algorithm.
        /// </summary>
        public static string PoolListAlgo {
            get {
                return ResourceManager.GetString("PoolListAlgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coin.
        /// </summary>
        public static string PoolListCoin {
            get {
                return ResourceManager.GetString("PoolListCoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee.
        /// </summary>
        public static string PoolListFee {
            get {
                return ResourceManager.GetString("PoolListFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mine.
        /// </summary>
        public static string PoolListMineButton {
            get {
                return ResourceManager.GetString("PoolListMineButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miners.
        /// </summary>
        public static string PoolListMiners {
            get {
                return ResourceManager.GetString("PoolListMiners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Hashrate.
        /// </summary>
        public static string PoolListNetworkHashrate {
            get {
                return ResourceManager.GetString("PoolListNetworkHashrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string PoolListPaymentScheme {
            get {
                return ResourceManager.GetString("PoolListPaymentScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pool Hashrate.
        /// </summary>
        public static string PoolListPoolHashrate {
            get {
                return ResourceManager.GetString("PoolListPoolHashrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Miners (24h).
        /// </summary>
        public static string PoolMiners {
            get {
                return ResourceManager.GetString("PoolMiners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payments.
        /// </summary>
        public static string PoolPayments {
            get {
                return ResourceManager.GetString("PoolPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;text-danger&quot;&gt;**IMPORTANT**:&lt;/span&gt; This pool is **not** yet active. It will be fully enabled around June 21, 2019..
        /// </summary>
        public static string PoolPending1 {
            get {
                return ResourceManager.GetString("PoolPending1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;text-danger&quot;&gt;**IMPORTANT**:&lt;/span&gt; The SUQA hardfork that will result in a rebranding of the SUQA project to Sinovate (SIN) has been delayed to block 170000, which will occur around June 1st, 2019.  In the meantime, you may use this pool to validate your X25x mining setup, just be aware that we **won&apos;t be able to hit/pay any blocks until the hardfork**.
        ///.
        /// </summary>
        public static string PoolPending2 {
            get {
                return ResourceManager.GetString("PoolPending2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pool Stats.
        /// </summary>
        public static string PoolStats {
            get {
                return ResourceManager.GetString("PoolStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pool Wallet.
        /// </summary>
        public static string PoolWallet {
            get {
                return ResourceManager.GetString("PoolWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span class=&quot;text-success&quot;&gt;**NOTE**:&lt;/span&gt; Hardfork activated at block {0}. Happy mining!.
        /// </summary>
        public static string PostHardforkNote {
            get {
                return ResourceManager.GetString("PostHardforkNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algorithm.
        /// </summary>
        public static string PowAlgo {
            get {
                return ResourceManager.GetString("PowAlgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quadrillion.
        /// </summary>
        public static string Quadrillion {
            get {
                return ResourceManager.GetString("Quadrillion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quickstart.
        /// </summary>
        public static string Quickstart {
            get {
                return ResourceManager.GetString("Quickstart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linux Quickstart.
        /// </summary>
        public static string QuickstartLinux {
            get {
                return ResourceManager.GetString("QuickstartLinux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Quickstart.
        /// </summary>
        public static string QuickstartWindows {
            get {
                return ResourceManager.GetString("QuickstartWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quintillion.
        /// </summary>
        public static string Quintillion {
            get {
                return ResourceManager.GetString("Quintillion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down from previous day.
        /// </summary>
        public static string QuoteDown24h {
            get {
                return ResourceManager.GetString("QuoteDown24h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up from previous day.
        /// </summary>
        public static string QuoteUp24h {
            get {
                return ResourceManager.GetString("QuoteUp24h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **ASIC BOOST**: This pool fully supports [Version-Rolling ASIC Boost](https://halongmining.com/blog/2018/03/07/dragonmint-btc-miner-uses-version-rolling-asicboost/) - also known as Overt ASIC Boost. This feature is supported on Halong Mining&apos;s DragonMint T1 and hardware based on Bitmain&apos;s BM1380 chip such as Antminer S9, R4, S9i, S9j, T9 and T9+..
        /// </summary>
        public static string RollingVersionAsicBoost {
            get {
                return ResourceManager.GetString("RollingVersionAsicBoost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to Start.
        /// </summary>
        public static string SetupGenerator {
            get {
                return ResourceManager.GetString("SetupGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Note:&lt;/b&gt; Using the @Strings.SetupGenerator is highly recommended if you are new to crypto mining.
        /// </summary>
        public static string SetupGeneratorHelp {
            get {
                return ResourceManager.GetString("SetupGeneratorHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solo.
        /// </summary>
        public static string SoloPool {
            get {
                return ResourceManager.GetString("SoloPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string StratumAddress {
            get {
                return ResourceManager.GetString("StratumAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;SSL:&lt;/b&gt; All ports support both SSL and non-SSL connections without any extra configuration (auto-sensing)..
        /// </summary>
        public static string StratumFeatures {
            get {
                return ResourceManager.GetString("StratumFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **LOGIN:** Login using your wallet address as username. An optional workername can be appended to your address separated by a dot (.) character. Password can be left blank..
        /// </summary>
        public static string StratumLogin {
            get {
                return ResourceManager.GetString("StratumLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Nicehash&lt;/b&gt;: Nicehash is supported on all ports..
        /// </summary>
        public static string StratumNicehash {
            get {
                return ResourceManager.GetString("StratumNicehash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficulty/Port.
        /// </summary>
        public static string StratumPortAndDifficulty {
            get {
                return ResourceManager.GetString("StratumPortAndDifficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stratum Configuration.
        /// </summary>
        public static string StratumPorts {
            get {
                return ResourceManager.GetString("StratumPorts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficulty.
        /// </summary>
        public static string StratumStartingDiff {
            get {
                return ResourceManager.GetString("StratumStartingDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Static difficulty**: To mine with a static (fixed) difficulty simply use &lt;code&gt;d=xxx&lt;/code&gt; as password where &lt;code&gt;xxx&lt;/code&gt; is your preferred difficulty..
        /// </summary>
        public static string StratumStaticDifficulty {
            get {
                return ResourceManager.GetString("StratumStaticDifficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topics.
        /// </summary>
        public static string Topics {
            get {
                return ResourceManager.GetString("Topics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trillion.
        /// </summary>
        public static string Trillion {
            get {
                return ResourceManager.GetString("Trillion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficulty will be automatically adjusted according to your hash power.
        /// </summary>
        public static string VarDiff {
            get {
                return ResourceManager.GetString("VarDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter wallet address.
        /// </summary>
        public static string WatermarkWalletAddress {
            get {
                return ResourceManager.GetString("WatermarkWalletAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem Ipsum.
        /// </summary>
        public static string WelcomeH1Fmt {
            get {
                return ResourceManager.GetString("WelcomeH1Fmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat..
        /// </summary>
        public static string WelcomeH2_1 {
            get {
                return ResourceManager.GetString("WelcomeH2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miners.
        /// </summary>
        public static string WorkerCount {
            get {
                return ResourceManager.GetString("WorkerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To mine directly to an exchange you need append your paymentId to your address separated by a hash sign.&lt;br/&gt;&lt;br/&gt;&lt;b&gt;Example: &lt;/b&gt;&lt;code&gt;&amp;lt;WALLET ADDRESS&amp;gt;&lt;/code&gt;#&lt;code&gt;&amp;lt;PAYMENT_ID&amp;gt;&lt;/code&gt;.&lt;code&gt;&amp;lt;WORKER&amp;gt;&lt;/code&gt;.
        /// </summary>
        public static string XmrExchangeInstructions {
            get {
                return ResourceManager.GetString("XmrExchangeInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This pool is compatible with the Monero RandomX November 2019 hard fork.
        /// </summary>
        public static string XmrHardforkInfo {
            get {
                return ResourceManager.GetString("XmrHardforkInfo", resourceCulture);
            }
        }
    }
}
